services:
  - type: web
    name: sih26139-qml-telemed
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PORT
        value: 8000
